Mudek/Mudek/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include
from django.conf.urls.static import static

# Local Django
from Mudek.views import ActivationView, ResetPasswordView
from core.api_views import TokenCreateView


urlpatterns = [
    # Admin
    path('edmsadmin/', admin.site.urls),

    # Api
    path('', include('Mudek.api_urls')),

    # Token
    path('api/auth/login/', TokenCreateView.as_view(), name='login'),
    path('api/auth/', include('djoser.urls.authtoken')),

    # Activation and Password Operations
    path('activation/(<key>)/', ActivationView.as_view(), name='activation'),
    path(
        'reset-password/(<key>)/',
        ResetPasswordView.as_view(),
        name='reset-password'
    ),

    # Web
    path('', include('edms.urls')),
    path('contact/', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mudek/core/urls.py
# Django
from django.urls import path

# Local Django
from .views import ContactView
app_name='core'

urlpatterns = [
   path('', ContactView.as_view(), name='contact'),
]

Mudek/edms/urls.py
# Django
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView,
    PasswordChangeView, PasswordChangeDoneView
)
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

# Local
from edms.views import *

app_name = 'edms'

urlpatterns = [
    # Lesson Links
    path('', LessonListView.as_view(), name='lesson-list'),
    path('lessons', LessonListView.as_view(), name='lesson-list'),
    path('lessons/<int:pk>', LessonDetailView.as_view(), name='lesson-detail'),
    path(
        'lessons/<int:pk>/update',
        LessonUpdateView.as_view(),
        name='lesson-update'
    ),

    # Exam Links
    path('exam/<int:pk>/update', ExamUpdateView.as_view(), name='exam-update'),

    # Other Document Links
    path(
        'other_document/<int:pk>/update',
        OtherDocumentUpdateView.as_view(),
        name='other-document-update'
    ),

    # Requsted Document Links
    path(
        'requsted_documents/<int:pk>/update',
        RequstedDocumentsUpdateView.as_view(),
        name='requsted-update'
    ),
    # User İnteraction
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {
        'template_name': 'registration/logout.html'},
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
]

Mudek/Mudek/forms.py
# Django
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import password_validation
from django.utils.translation import ugettext_lazy as _

# Local Django
from users.models import User


class ResetPasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput,
        strip=False,
        required=True,
        help_text=password_validation.password_validators_help_text_html(),
    )
    confirm_password = forms.CharField(
        label=_('Confirm Password'),
        widget=forms.PasswordInput,
        strip=False,
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
            else:
                password_validation.validate_password(confirm_password)

        return self.cleaned_data

    def save(self, key, commit=True):
        user = None

        if commit:
            # Set Password
            user = key.user
            user.set_password(self.cleaned_data['password'])
            user.save()

            # Key Updated
            key.is_used = True
            key.save()

        return user

Mudek/Mudek/views.py
# Django
from django.conf import settings
from django.contrib import messages
from django.views.static import serve
from django.views.generic import View
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _

# Local Django
from users.models import ActivationKey
from Mudek.forms import ResetPasswordForm
from Mudek.variables import RESET_PASSWORD_FORM_PREFIX
from Mudek.modules import ActivationKeyModule, ResetPasswordKeyModule


class ActivationView(TemplateView):
    template_name = 'activation.html'

    def dispatch(self, request, key, *args, **kwargs):
        self.activation(key)

        if request.user.is_authenticated():
            if self.activation_key:
                messages.success(request, self.activation_message)
            else:
                messages.error(request, self.activation_message)

            return redirect('/admin/')

        return super(ActivationView, self).dispatch(
            request, key, *args, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(ActivationView, self).get_context_data(**kwargs)

        context.update({
            'title': 'Activation',
            'domain_frontend': settings.DOMAIN_FRONTEND,
            'activation_key': self.activation_key,
            'activation_message': self.activation_message
        })

        return context

    def activation(self, key):
        self.activation_message = ''
        self.activation_key = ActivationKeyModule.get_key(key)

        if self.activation_key:
            # User verified.
            self.activation_key.user.is_verified = True
            self.activation_key.user.save()

            # Key disabled.
            self.activation_key.is_used = True
            self.activation_key.save()

            self.activation_message = _('Activation is successfully completed.')
        else:
            self.activation_message = _('Incorrect key!')


class ResetPasswordView(TemplateView):
    template_name = 'reset-password.html'

    def dispatch(self, request, key, *args, **kwargs):
        self.reset_password_message = ''
        self.reset_password_key = None
        self.reset_password_error = False
        self.reset_password_success = False
        self.check_key(key)

        if not self.reset_password_key:
            self.reset_password_error = True

        return super(ResetPasswordView, self).dispatch(
            request, key, *args, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)

        context.update({
            'title': _('Reset Password'),
            'domain_frontend': settings.DOMAIN_FRONTEND,
            'reset_password_key': self.reset_password_key,
            'reset_password_error': self.reset_password_error,
            'reset_password_success': self.reset_password_success,
            'reset_password_message': self.reset_password_message,
            'reset_password_form': ResetPasswordForm(
                prefix=RESET_PASSWORD_FORM_PREFIX
            )
        })

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()

        if RESET_PASSWORD_FORM_PREFIX in request.POST:
            reset_password_form = ResetPasswordForm(
                self.request.POST, prefix=RESET_PASSWORD_FORM_PREFIX
            )

            if reset_password_form.is_valid():
                user = reset_password_form.save(self.reset_password_key)

                if not user:
                    self.reset_password_error = True
                else:
                    self.reset_password_success = True
                    self.reset_password_message = _(
                        _('Your password has been successfully determined.')
                    )

            context.update({
                'reset_password_form': reset_password_form,
                'reset_password_error': self.reset_password_error,
                'reset_password_success': self.reset_password_success,
                'reset_password_message': self.reset_password_message
            })

        return super(ResetPasswordView, self).render_to_response(context)

    def check_key(self, key):
        self.reset_password_key = ResetPasswordKeyModule.get_key(key)

        if not self.reset_password_key:
            self.reset_password_message = _('Incorrect or used key!')

Mudek/Mudek/templates/activation.html
{% extends "admin/base_site.html" %}

{% load i18n admin_static staticfiles %}


{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/login.css' %}">

  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block branding %}
  <div style="float: none; text-align: center; line-height: normal;">
    <img src="{% static 'img/logos/logo.png' %}" alt="logo" height="48">
  </div>
{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
  {% if activation_key %}
    <p class="errornote" style="color:#33CC00; border: 1px solid #33CC00; text-align: center;">
      {{ activation_message }}

      {% if domain_frontend %}
        <br> <a style="text-align: center;" href="{{ domain_frontend }}">
          {% trans 'Log in' %}
        </a>
      {% endif %}
    </p>
  {% else %}
    <p class="errornote" style="text-align: center;">
      {{ activation_message }}
    </p>
  {% endif %}
{% endblock %}

Mudek/Mudek/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}EDMS{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" 
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" 
        crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Francois+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans&display=swap" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" 
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" 
        crossorigin="anonymous"></script>

    <!-- CSS import-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'img/icons/favicon.png' %}" />
    <!-- Java script import -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
</head>
<style>
select{
    color: #0D0D0D;
  }

select option {
    margin: 40px;
    background: #448FF2;
    color: #fff;
    text-shadow: 0 1px 0 #448FF2;
}
textarea {
    color:black;
    }
</style>
<body>
       
    
    {% include "header.html" %}
    {% include 'messages.html' %}
    {% block body %}
    
    {% endblock %}

</body>
</html>

Mudek/Mudek/templates/header.html
{% load i18n staticfiles %}
<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    <div class="edms" >
        <a class="edms" href="{% url 'edms:lesson-list' %}"><img src="{% static 'img/icons/favicon.png' %}"></a>
        <a class="navbar-brand" href="{% url 'edms:lesson-list' %}">&nbsp; EDMS</a>
    </div>
    
        
    </div>
    {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <li class=""><a href="{% url 'edms:password_change' %}">
                <span class="glyphicon glyphicon-lock" aria-hidden="true">
                </span>&nbsp; Change Password</a>
            </li>
            <li class=""><a href="{% url 'edms:logout' %}">
                <span class="glyphicon glyphicon-off" aria-hidden="true">
                </span>&nbsp; Logout</a>
            </li>
            <li class=""><a href="{% url 'core:contact' %}">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true">
                </span>&nbsp; Contact</a>
            </li>
            
        </ul>
    {% else %}
        <ul class="nav navbar-nav navbar-right">
            <li class=""><a href="{% url 'edms:login' %}">
                <span class="glyphicon glyphicon-user" aria-hidden="true">
                </span>&nbsp; Login</a>
            </li>
            <li class=""><a href="/edmsadmin">
                <span class="glyphicon glyphicon-cog" aria-hidden="true">
                </span>&nbsp; Admin Login</a>
            </li>
            <li class=""><a href="{% url 'core:contact' %}">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true">
                </span>&nbsp; Contact</a>
            </li>
        </ul>
        
    {% endif %}
   
</div>
</nav>

Mudek/Mudek/templates/messages.html
{% if messages %}
    <div  class="message">
        {% for message in messages %}
        <p class="alert alert-dismissable {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </p>
        {% endfor %}
    </div>
    {% endif %}

Mudek/Mudek/templates/reset-password.html
{% extends "admin/base_site.html" %}

{% load i18n static %}
{% load core_extras %}


{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/login.css' %}" />

  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block branding %}
  <div style="float: none; text-align: center; line-height: normal;">
    <img src="{% static 'img/logos/logo.png' %}" alt="logo" height="48">
  </div>
{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}

  {% if success %}
    <p class="errornote" style="text-align: center;">
      {{ success }}
    </p>
  {% endif %}

  {% if reset_password_error %}
    <br>
    <p class="errornote" style="text-align: center;">
      {{ reset_password_message }}
    </p>
  {% elif reset_password_success %}
    <br>
    <p class="errornote" style="color:#33CC00; border: 1px solid #33CC00; text-align: center;">
      {{ reset_password_message }}

      {% if domain_frontend %}
        <br> <a style="text-align: center;" href="{{ domain_frontend }}">
          {% trans 'Log in' %}
        </a>
      {% endif %}
    </p>
  {% else %}
    <p class="errornote" style="color:#999900; border: 1px solid #999900;">
      {% blocktrans with reset_password_key_user=reset_password_key.user %}Welcome, {{ reset_password_key_user }} <br>Let's determine the password.{% endblocktrans %}
    </p>

    {% if reset_password_form.errors and not form.non_field_errors %}
      <p class="errornote">
        {% if reset_password_form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
      </p>
    {% endif %}

    {% if reset_password_form.non_field_errors %}
      {% for error in reset_password_form.non_field_errors %}
      <p class="errornote">
          {{ error }}
      </p>
      {% endfor %}
    {% endif %}

    <div id="content-main">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-row">
          {{ reset_password_form.password.errors }}
          {{ reset_password_form.password.label_tag }} {% add_attrs reset_password_form.password style="width: 100%; padding: 8px; box-sizing: border-box;" %}
        </div>
        <div class="form-row">
          {{ reset_password_form.confirm_password.errors }}
          {{ reset_password_form.confirm_password.label_tag }} {% add_attrs reset_password_form.confirm_password style="width: 100%; padding: 8px; box-sizing: border-box;" %}
        </div>
        <div class="submit-row submit-row-padding">
          <label>&nbsp;</label><input type="submit" name="{{ reset_password_form.prefix }}" value="{% trans 'Send' %}" />
        </div>
      </form>
    </div>
  {% endif %}

{% endblock %}