Mudek/Mudek/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include
from django.conf.urls.static import static

# Local Django
from Mudek.views import ActivationView, ResetPasswordView
from core.api_views import TokenCreateView


urlpatterns = [
    # Admin
    path('edmsadmin/', admin.site.urls),

    # Api
    path('', include('Mudek.api_urls')),

    # Token
    path('api/auth/login/', TokenCreateView.as_view(), name='login'),
    path('api/auth/', include('djoser.urls.authtoken')),

    # Activation and Password Operations
    path('activation/(<key>)/', ActivationView.as_view(), name='activation'),
    path(
        'reset-password/(<key>)/',
        ResetPasswordView.as_view(),
        name='reset-password'
    ),

    # Web
    path('', include('edms.urls')),
    path('contact/', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mudek/core/urls.py
# Django
from django.urls import path

# Local Django
from .views import ContactView
app_name='core'

urlpatterns = [
   path('', ContactView.as_view(), name='contact'),
]

Mudek/edms/urls.py
# Django
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView,
    PasswordChangeView, PasswordChangeDoneView
)
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

# Local
from edms.views import *

app_name = 'edms'

urlpatterns = [
    # Lesson Links
    path('', LessonListView.as_view(), name='lesson-list'),
    path('lessons', LessonListView.as_view(), name='lesson-list'),
    path('lessons/<int:pk>', LessonDetailView.as_view(), name='lesson-detail'),
    path(
        'lessons/<int:pk>/update',
        LessonUpdateView.as_view(),
        name='lesson-update'
    ),

    # Exam Links
    path('exam/<int:pk>/update', ExamUpdateView.as_view(), name='exam-update'),

    # Other Document Links
    path(
        'other_document/<int:pk>/update',
        OtherDocumentUpdateView.as_view(),
        name='other-document-update'
    ),

    # Requsted Document Links
    path(
        'requsted_documents/<int:pk>/update',
        RequstedDocumentsUpdateView.as_view(),
        name='requsted-update'
    ),
    # User İnteraction
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {
        'template_name': 'registration/logout.html'},
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
]

Mudek/edms/models.py
# Standart Library
import os

# Django
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.urls import reverse
from django.core.exceptions import ValidationError



def lesson_directory_path(instance, filename):
    return 'user {0}/{1}'.format(instance.user.email, filename)

def other_directory_path(instance, filename):
    return 'user {0}/{1}'.format(instance.lesson.user.email, filename)


def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = [
        '.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls'
    ]
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')


class Lesson(models.Model):
    user = models.ForeignKey(
        verbose_name=_('User'),
        to='users.User',
        on_delete=models.CASCADE,
        related_name='lessons'
    )
    lesson_name = models.CharField(verbose_name=_('Ders Adı'), max_length=150)
    lesson_content = models.TextField(
        verbose_name=_('Ders İçeriği'),
        blank=True
    )
    lesson_content_file = models.FileField(
        verbose_name=_('Ders İçeriği Dosya'), blank=True, null=True,
        upload_to=lesson_directory_path, validators=[validate_file_extension]
    )
    lesson_notes = models.TextField(verbose_name=_('Ders Notu'), blank=True)
    lesson_notes_file = models.FileField(
        verbose_name=_('Ders Notu Dosya'),
        blank=True, null=True,
        upload_to=lesson_directory_path, validators=[validate_file_extension]
    )

    def __str__(self):
        return '{lesson_name}'.format(
            lesson_name=self.lesson_name
        )

    class Meta:
        verbose_name = 'Lesson'
        verbose_name_plural = 'Lesson'


class Exam(models.Model):
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE
    )
    exam_type = models.CharField(
        verbose_name=_('Sınav Türü'), max_length=50, blank=True, null=True
    )
    exam_information = models.TextField(
        verbose_name=_('Sınav Hakkında Bilgi'),
        max_length=500, blank=True, null=True
    )
    exam_file = models.FileField(
        verbose_name=_('Sınav Kağıdı Dosya'), blank=True, null=True,
        upload_to=other_directory_path, validators=[validate_file_extension]
    )
    exam_answer_file = models.FileField(
        verbose_name=_('Cevap Anahtarı Dosya'), blank=True, null=True,
        upload_to=other_directory_path, validators=[validate_file_extension]
    )

    def __str__(self):
        return '{lesson} - {exam_type}'.format(
            lesson=self.lesson.lesson_name,
            exam_type=self.exam_type
        )

    class Meta:
        verbose_name = 'Exam'
        verbose_name_plural = 'Exam'


class Requested_Documents(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    d_name = models.CharField(
        verbose_name=_('İstenilen Belge Adı'),
        max_length=100
    )
    d_bool = models.BooleanField(
        verbose_name=_('İstenilen Belge Yüklü mü ?'),
        default=False
    )

    def __str__(self):
        return '{d_name}'.format(
            d_name=self.d_name
        )

    class Meta:
        verbose_name = 'Requested Documents'
        verbose_name_plural = 'Requested Documents'


class Other_Document(models.Model):
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE
    )
    name = models.ForeignKey(
        Requested_Documents,
        on_delete=models.CASCADE
    )

    document = models.FileField(
        verbose_name=_('Dosya'), blank=True, null=True,
        upload_to=other_directory_path, validators=[validate_file_extension]
    )

    def __str__(self):
        return '{name}'.format(
            name=self.name.d_name
        )

    class Meta:
        verbose_name = 'Other Document'
        verbose_name_plural = 'Other Document'

Mudek/edms/forms.py
from django import forms
from .models import Lesson, Other_Document, Requested_Documents
from django.contrib.auth import authenticate


class LessonForm(forms.ModelForm):

    class Meta:
        model = Lesson
        fields = [
        'lesson_content', 'lesson_content_file',
        'lesson_notes', 'lesson_notes_file'
    ]

class OtherDocumentForm(forms.ModelForm):

    class Meta:
        model = Other_Document
        fields = ['lesson', 'document']

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'contatct-form'}))
    password = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("User does not exist.")
            if not user.is_active:
                raise forms.ValidationError("User is no longer active.")
        return super(LoginForm, self).clean(*args, **kwargs)

Mudek/Mudek/views.py
# Django
from django.conf import settings
from django.contrib import messages
from django.views.static import serve
from django.views.generic import View
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _

# Local Django
from users.models import ActivationKey
from Mudek.forms import ResetPasswordForm
from Mudek.variables import RESET_PASSWORD_FORM_PREFIX
from Mudek.modules import ActivationKeyModule, ResetPasswordKeyModule


class ActivationView(TemplateView):
    template_name = 'activation.html'

    def dispatch(self, request, key, *args, **kwargs):
        self.activation(key)

        if request.user.is_authenticated():
            if self.activation_key:
                messages.success(request, self.activation_message)
            else:
                messages.error(request, self.activation_message)

            return redirect('/admin/')

        return super(ActivationView, self).dispatch(
            request, key, *args, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(ActivationView, self).get_context_data(**kwargs)

        context.update({
            'title': 'Activation',
            'domain_frontend': settings.DOMAIN_FRONTEND,
            'activation_key': self.activation_key,
            'activation_message': self.activation_message
        })

        return context

    def activation(self, key):
        self.activation_message = ''
        self.activation_key = ActivationKeyModule.get_key(key)

        if self.activation_key:
            # User verified.
            self.activation_key.user.is_verified = True
            self.activation_key.user.save()

            # Key disabled.
            self.activation_key.is_used = True
            self.activation_key.save()

            self.activation_message = _('Activation is successfully completed.')
        else:
            self.activation_message = _('Incorrect key!')


class ResetPasswordView(TemplateView):
    template_name = 'reset-password.html'

    def dispatch(self, request, key, *args, **kwargs):
        self.reset_password_message = ''
        self.reset_password_key = None
        self.reset_password_error = False
        self.reset_password_success = False
        self.check_key(key)

        if not self.reset_password_key:
            self.reset_password_error = True

        return super(ResetPasswordView, self).dispatch(
            request, key, *args, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)

        context.update({
            'title': _('Reset Password'),
            'domain_frontend': settings.DOMAIN_FRONTEND,
            'reset_password_key': self.reset_password_key,
            'reset_password_error': self.reset_password_error,
            'reset_password_success': self.reset_password_success,
            'reset_password_message': self.reset_password_message,
            'reset_password_form': ResetPasswordForm(
                prefix=RESET_PASSWORD_FORM_PREFIX
            )
        })

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()

        if RESET_PASSWORD_FORM_PREFIX in request.POST:
            reset_password_form = ResetPasswordForm(
                self.request.POST, prefix=RESET_PASSWORD_FORM_PREFIX
            )

            if reset_password_form.is_valid():
                user = reset_password_form.save(self.reset_password_key)

                if not user:
                    self.reset_password_error = True
                else:
                    self.reset_password_success = True
                    self.reset_password_message = _(
                        _('Your password has been successfully determined.')
                    )

            context.update({
                'reset_password_form': reset_password_form,
                'reset_password_error': self.reset_password_error,
                'reset_password_success': self.reset_password_success,
                'reset_password_message': self.reset_password_message
            })

        return super(ResetPasswordView, self).render_to_response(context)

    def check_key(self, key):
        self.reset_password_key = ResetPasswordKeyModule.get_key(key)

        if not self.reset_password_key:
            self.reset_password_message = _('Incorrect or used key!')

Mudek/edms/views.py
# Django
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, FormView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Local
from edms.models import Lesson, Exam, Other_Document, Requested_Documents
from users.models import User
from .forms import LessonForm, OtherDocumentForm, LoginForm


class LoginView(FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm
    success_url = '/lessons'

    def form_valid(self, form):
        form = LoginForm(self.request.POST or None)
        if form.is_valid():
            email = self.request.POST.get('email')
            password = self.request.POST.get('password')
            user = authenticate(email=email, password=password)
            login(self.request, user)
            return redirect('edms:lesson-list')
        return render(self.request, self.template_name , {'form':form})


class LessonListView(ListView):
    model = Lesson
    template_name = 'edms/lesson/list.html'
    success_url = '/lessons'
    
    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
            if user.is_department_manager or user.is_assistant_department_manager or user.is_dean_manager:
                documnets = Requested_Documents.objects.filter(
                    lesson__user=user
                ).order_by("lesson")
                lessons = {}
                all_lessons = Lesson.objects.all()            
                for lesson in all_lessons:
                    lesson_id = str(lesson.id)
                    lessons[lesson_id] = {
                            'lesson': lesson,
                            'docs': []
                        }

                for doc in documnets:
                    lesson_id = str(doc.lesson.id)
                    lessons[lesson_id]['docs'].append(doc)
                return render(request, self.template_name, {
                    'lessons': lessons
                })
            elif user.is_academician:
                documnets = Requested_Documents.objects.filter(
                    lesson__user=user
                ).order_by("lesson")

                lessons = {}
                for lesson in Lesson.objects.filter(user=user):
                    lesson_id = str(lesson.id)
                    lessons[lesson_id] = {
                            'lesson': lesson,
                            'docs': []
                        }

                for doc in documnets:
                    lesson_id = str(doc.lesson.id)
                    lessons[lesson_id]['docs'].append(doc)

                return render(request, self.template_name, {
                    'lessons': lessons,
                })
        else:
            return redirect(reverse('edms:login'))


class LessonDetailView(DetailView):
    model = Lesson
    template_name = 'edms/lesson/detail.html'


class LessonUpdateView(SuccessMessageMixin, UpdateView):
    model = Lesson
    template_name = 'edms/lesson/update.html'
    form_class = LessonForm
    
    success_url = "/lessons"
    success_message = 'Lesson successfully saved!!!!'

    def update(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(LessonUpdateView, self).update(request, *args, **kwargs)


class ExamUpdateView(SuccessMessageMixin, UpdateView):
    model = Exam
    template_name = 'edms/exam/update.html'
    fields = ['exam_information', 'exam_file', 'exam_answer_file']
    success_url = "/lessons"
    success_message = 'Exam successfully saved!!!!'

    def update(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ExamUpdateView, self).update(request, *args, **kwargs)


class OtherDocumentUpdateView(SuccessMessageMixin, UpdateView):
    model = Other_Document
    template_name = 'edms/other/update.html'
    form_class = OtherDocumentForm
    success_url = "/lessons"
    success_message = 'Other Document successfully saved!!!!'

    def update(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(OtherDocumentUpdateView, self).update(request, *args, **kwargs)


class RequstedDocumentsUpdateView(SuccessMessageMixin, UpdateView):
    model = Requested_Documents
    template_name = 'edms/requested/update.html'
    fields = ['d_bool', ]
    success_url = "/lessons"
    success_message = 'Requsted Document successfully saved!!!!'

    def update(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(RequstedDocumentsUpdateView, self).update(request, *args, **kwargs)

Mudek/Mudek/templates/edms/lesson/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container-fluid">
    <div class="lessonheader">
        <h1>{{ object.lesson_name }} </h1>
        
    </div>
</div>

<div class="col-sm-8 col-md-9 block-content">
    <ul class="nav nav-pills" style="margin-bottom: 30px;"></ul>
    
    <div class="panel panel-info">
        <div class="panel-heading">
                Lesson Content
        </div>
        

        <div class="panel-body">
            <h5>{{ object.lesson_content|safe }}</h5>
            {% if object.lesson_content_file %}
                <h5><a class="btn btn-show" role="button" target="_blank" href="{{ object.lesson_content_file.url }}">Show Course Content</a></h5>
            {% endif %}
            <a href="{% url 'edms:lesson-update' pk=lesson.pk %}" class="btn btn-update" role="button">Update Lesson</a>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            Lesson Note
        </div>
        <div class="panel-body">
            <h5>{{ object.lesson_notes|safe }}</h5>
            {% if object.lesson_notes_file %}
                <h5><a class="btn btn-show" role="button" target="_blank" href="{{ object.lesson_notes_file.url }}">Note Show Content</a></h5>
            {% endif %}
            <a href="{% url 'edms:lesson-update' pk=lesson.pk %}" class="btn btn-update" role="button">Update Lesson</a>
        </div>
    </div>

    <div class="exam">
    {% if object.exam_set.all %}
        {% for exam in object.exam_set.all %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ exam.exam_type }}
                </div>
                <div class="panel-body">
                    {% if exam.exam_type %}
                        <h5>{{ exam.exam_information|safe }}</h5>
                    {% endif %}
                    {% if exam.exam_file %}
                        <h5><a class="btn btn-show" role="button" target="_blank" href="{{ exam.exam_file.url }}">Show Exam Paper</a></h5>
                    {% endif %}
                    {% if exam.exam_answer_file %}
                        <h5><a class="btn btn-show" role="button" target="_blank" href="{{ exam.exam_answer_file.url }}">Show Answer Paper</a></h5>
                    {% endif %}
                    <a href="{% url 'edms:exam-update' pk=exam.pk %}" class="btn btn-update" role="button">Update Exam</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="other">
        {% for other in object.other_document_set.all %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ other.lesson }} Other Documents
                </div>
                <div class="panel-body">
                    {{ other.name }}
                    <a href="{% url 'edms:other-document-update' pk=other.pk %}" class="btn btn-update" role="button">Update Other Document</a>
                </div>
            </div>
            
        {% endfor %}
    </div>
</div>
{% endblock %}

Mudek/Mudek/templates/edms/lesson/list.html
{% extends 'base.html' %}
{% include 'messages.html' %}
{% block body %}
<div class="container">
    <div class="thumbnail1">
        {% if lessons %}
            {% for key, lesson in lessons.items %}
                <div class="thumbnail">
                        <h5 class="lessonname">{{ lesson.lesson.user.first_name }} {{ lesson.lesson.user.last_name }}</h5>
                    <a href="{% url 'edms:lesson-detail' pk=lesson.lesson.pk %}">
                        <h2 class="lessonname">{{ lesson.lesson.lesson_name|safe|linebreaks|truncatechars:150 }}</h2>
                    </a>
                    {% for request in lesson.docs %}
                    <div class="r_docs">
                        <ul>
                            <input {% if request.d_bool %}checked="checked"{% endif %} type="checkbox"/>
                            <a class="r_doc" href="{% url 'edms:requsted-update' pk=request.pk %}" role="button">{{ request.d_name }}</a>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

Mudek/Mudek/templates/edms/lesson/update.html
{% extends 'base.html' %}


{% block body %}

    <div class="container">
        <div class="thumbnail1">
            <div class="updateform">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ form.media }}
                    <input class="btn btn-update" type="submit" value="Lesson Save">
                </form>
        </div>
        </div>
    </div>

{% endblock %}